name: generate animation

on:
  # بيحدث نفسه كل 24 ساعة
  schedule:
    - cron: "0 */24 * * *" 
  
  # بيسمحلك تشغله يدوي في أي وقت
  workflow_dispatch:
  
  # بيشتغل كل ما ترفع كود (Push) على برانش main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # بيولد صورة التعبان من الـ Contributions بتاعتك
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: zeyadabmonem
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # بيرفع الصورة في برانش مخفي اسمه output عشان الـ README يشوفها
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
